@extends('page', ['body_class' => 'landing'])
@section('title')
- Disclaimer
@endsection
@section('content')
        <div class="body">
            <div class="wrap">
                <h1 align="center">Disclaimer</h1>
                <p>The following describes the Disclaimer for our Pimboo.com website.</p>
                <p>THIRD PARTY NOTICE: You understand, acknowledge, and accept the fact that we at Too Brains AB are not affiliated with any company, person, or organization of any kind mentioned on this Pimboo.com website in any way.&nbsp; Company names, products, logos, trade marks and any other proprietary intellectual property or otherwise belongs to the rightful owner, which is not us.&nbsp; You should not assume, even if a company name is in the website/domain name of this website, that there is an express, implied, or otherwise agreement, joint venture, partnership, or other relationship between us as website proprietors and any of these companies that are discussed merely for educational or other purposes.
                </p>
                <p>The opinions, estimates, expectations, and projections contained in any disseminated information are accurate as of the date of release and are subject to change without additional notice. We do our best to ensure that the research has been compiled, obtained, discerned, or interpolated from reliable and trustworthy sources, and therefore believe the positions and beliefs shared are accurate and complete, though obviously not all material known or obtained will be contained, as distilling information into manageable quantity is in large part a goal.&nbsp; We at Too Brains AB are not responsible for any errors or omissions contained in any disseminated material and are not liable for any loss incurred as a result of using the material in any way.&nbsp; The intent is merely to provide useful information, products, and services, some of which we may be compensated for.</p>
                <p>Nothing offered by Too Brains AB should be considered personalized investment advice. While our employees and/or contributors may answer your general customer service questions, they can not help you with specific investment questions and decisions, as they are not licensed under securities laws to deal with your particular investment situation. No communication by our employees and/or contributors to you should be construed as personal, individualized investment advice.&nbsp; Investors should not rely on the information given by us to make investment decisions.&nbsp; Rather, investors should use the information at Pimboo.com only as a starting point, at most, to do additional independent research so that the investor is able to make his or her own investment decision.&nbsp; You should consult with competent, professional help and read any available Prospectus or Public Company information.</p>
                <p>This Pimboo.com website contains or may contain “forward looking statements” within the meaning of Section 27A of the Securities Act of1933 and Section 21B of the Securities Exchange Act of1934.&nbsp; Any statements that express or involve discussions with respect to predictions, expectations, beliefs, plans, projections, objectives, goals, assumptions or future events or performance are not statements of historical fact and may be “forward looking statements.”&nbsp; Forward looking statements are based on expectations, estimates and projections at the time the statements are made that involve a number of risks and uncertainties which could cause actual results or events to differ materially from those presently anticipated.&nbsp; Forward looking statements in this action may be identified through the use of words such as “expects”, “will,” “anticipates,” “estimates,” “believes,” or statements indicating certain actions “may,” “could,” or “might” occur.</p>
                <p>Just as our website content does not constitute investment advice, and you should therefore consult a trained professional of your choosing, the same is true of other disciplines where expertise is gained through education, experience, and skill-building.&nbsp; Thus, nothing on our website or otherwise disseminated by Too Brains AB in conjunction with it should be taken as medical, legal, accounting or other such advice.&nbsp; When in doubt, consult the hired help of your choosing, as you are ultimately responsible for your own affairs.</p>
                <p><strong>CHANGE NOTICE:</strong><br>
                As with any of our administrative and legal notice pages, the contents of this page can and will change over time.&nbsp; Accordingly, this page could read differently as of your very next visit.&nbsp; These changes are necessitated, and carried out by Too Brains AB, in order to protect you and our Pimboo.com website.&nbsp; If this page is important to you, you should check back frequently as no other notice of changed content will be provided either before or after the change takes effect.</p>
                <p><strong>COPYRIGHT WARNING:</strong><br>
                The legal notices and administrative pages on this website, including this one, have been diligently drafted by an attorney.&nbsp; We at Too Brains AB have paid to license the use of these legal notices and administrative pages on Pimboo.com for your protection and ours.&nbsp; This material may not be used in any way for any reason and unauthorized use is policed via Copyscape to detect violators.</p>
                <p><strong>QUESTIONS/COMMENTS/CONCERNS:</strong><br>
                If you have any questions about the contents of this page, or simply wish to reach us for any other reason, you may do so by using our Contact information.</p>
                <p style="text-align: center;">Too Brains AB, Stureplan 4C. 4th floor, 114 35 Stockholm, Sweden<br>
                PHONE: +46 76 308 6574</p>
            </div>
        </div>
@endsection
